services:
  cloud-agent:
    image: cloud-agent:1.0.0.10002
    environment:
      MQTT_BROKER: "tcp://emqx:1883"
      MQ_BROKER: "kafka:9092"
      MQ_CONSUMER_GROUP: "cloud-agent"
      GIN_MODE: "release"
      DEMO_TEST: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    sysctls:
      net.ipv4.ip_local_port_range: "1024 65535"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    extra_hosts:
      - "emqx:192.168.149.31"
      - "kafka:192.168.149.10"
